-- MySQL Script generated by MySQL Workbench
-- Mon Jan 14 11:17:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Technovision
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Technovision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Technovision` DEFAULT CHARACTER SET utf8 ;
USE `Technovision` ;

-- -----------------------------------------------------
-- Table `Technovision`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Technovision`.`users` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `fullName` VARCHAR(150) NOT NULL,
  `nic` VARCHAR(12) NOT NULL,
  `contactNumber` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `nic_UNIQUE` (`nic` ASC) VISIBLE,
  UNIQUE INDEX `contactNumber_UNIQUE` (`contactNumber` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
