-- MySQL Script generated by MySQL Workbench
-- Wed Jan 16 16:44:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Technovision
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Technovision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Technovision` DEFAULT CHARACTER SET utf8 ;
USE `Technovision` ;

-- -----------------------------------------------------
-- Table `Technovision`.`lense_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Technovision`.`lense_orders` (
  `receipt_number` VARCHAR(7) NOT NULL,
  `order_number` VARCHAR(6) NOT NULL,
  `customer_id` INT NOT NULL,
  `job_type` VARCHAR(11) NOT NULL,
  `tested_by` VARCHAR(50) NOT NULL,
  `lenses_total` DOUBLE NOT NULL,
  `advance` DOUBLE NULL,
  `balance` DOUBLE NULL,
  `old_right_sph` VARCHAR(10) NULL,
  `old_right_cyl` VARCHAR(10) NULL,
  `old_right_axis` VARCHAR(10) NULL,
  `old_right_add` VARCHAR(10) NULL,
  `old_left_sph` VARCHAR(10) NULL,
  `old_left_cyl` VARCHAR(10) NULL,
  `old_left_axis` VARCHAR(10) NULL,
  `old_left_add` VARCHAR(10) NULL,
  `present_right_sph` VARCHAR(10) NULL,
  `present_right_cyl` VARCHAR(10) NULL,
  `present_right_axis` VARCHAR(10) NULL,
  `present_right_add` VARCHAR(10) NULL,
  `present_left_sph` VARCHAR(10) NULL,
  `present_left_cyl` VARCHAR(10) NULL,
  `present_left_axis` VARCHAR(10) NULL,
  `present_left_add` VARCHAR(10) NULL,
  `right_bc` VARCHAR(10) NULL,
  `right_pow` VARCHAR(10) NULL,
  `right_dia` VARCHAR(10) NULL,
  `right_desz` VARCHAR(10) NULL,
  `left_bc` VARCHAR(10) NULL,
  `left_pow` VARCHAR(10) NULL,
  `left_dia` VARCHAR(10) NULL,
  `left_desz` VARCHAR(10) NULL,
  `trail_lense` VARCHAR(150) NULL,
  `over_refract` VARCHAR(45) NULL,
  `k_reading` VARCHAR(45) NULL,
  `blink_test` VARCHAR(45) NULL,
  `special_instractions` VARCHAR(225) NULL,
  `remarks` VARCHAR(225) NULL,
  `order_status` VARCHAR(45) NULL DEFAULT 'PENDING',
  `order_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `payment_plan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`receipt_number`),
  UNIQUE INDEX `recipt_id_UNIQUE` (`receipt_number` ASC) VISIBLE,
  UNIQUE INDEX `order_number_UNIQUE` (`order_number` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
